### ISSUE TITLE
Synthesize--ValueError: could not convert string to float: 'training_data/mels\\speech-mel-00001.npy'

### ISSUE THREAD

**Issue by Rita-ritally** [rishikksh20/vae_tacotron2#9]
when i ran python synthesize.py --model ='Tacotron'--mode ='eval'--reference_audio ='ref_1.wav' ,an issue occured!
ValueError: could not convert string to float: 'training_data/mels\\speech-mel-00001.npy'
![image](https://user-images.githubusercontent.com/45085467/92366821-36e22e80-f128-11ea-874d-9b48ad82c7e2.png)
please help me solving this problem
thanks!!!

**Comment by Rita-ritally** [comment]
`Loading checkpoint: logs-Tacotron/pretrained/model.ckpt-9500
Loaded metadata for 13100 examples (23.94 hours)
starting synthesis
  0%|                                                                                                             | 0/13100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "synthesize.py", line 34, in <module>
    main()
  File "synthesize.py", line 28, in main
    tacotron_synthesize(args)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 79, in tacotron_synthesize
    run_synthesis(args, checkpoint_path, output_dir)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 60, in run_synthesis
    mel_output_filename = synth.synthesize(text, None, i+1, synth_dir, None, mel_filename)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesizer.py", line 58, in synthesize
    reference_mel = [np.asarray(reference_mel, dtype=np.float32)]
  File "D:\Anaconda3\envs\tf1.6\lib\site-packages\numpy\core\numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'training_data/mels\\speech-mel-00001.npy'`

**Comment by Rita-ritally** [comment]
`Loading checkpoint: logs-Tacotron/pretrained/model.ckpt-9500
Loaded metadata for 13100 examples (23.94 hours)
starting synthesis
  0%|                                                                                                             | 0/13100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "synthesize.py", line 34, in <module>
    main()
  File "synthesize.py", line 28, in main
    tacotron_synthesize(args)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 79, in tacotron_synthesize
    run_synthesis(args, checkpoint_path, output_dir)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 60, in run_synthesis
    mel_output_filename = synth.synthesize(text, None, i+1, synth_dir, None, mel_filename)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesizer.py", line 58, in synthesize
    reference_mel = [np.asarray(reference_mel, dtype=np.float32)]
  File "D:\Anaconda3\envs\tf1.6\lib\site-packages\numpy\core\numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'training_data/mels\\speech-mel-00001.npy'`

**Comment by Rita-ritally** [comment]
Loading checkpoint: logs-Tacotron/pretrained/model.ckpt-9500
Loaded metadata for 13100 examples (23.94 hours)
starting synthesis
  0%|                                                                                                             | 0/13100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "synthesize.py", line 34, in <module>
    main()
  File "synthesize.py", line 28, in main
    tacotron_synthesize(args)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 79, in tacotron_synthesize
    run_synthesis(args, checkpoint_path, output_dir)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesize.py", line 60, in run_synthesis
    mel_output_filename = synth.synthesize(text, None, i+1, synth_dir, None, mel_filename)
  File "E:\cuc\2020\code\vae_tacotron2\tacotron\synthesizer.py", line 58, in synthesize
    reference_mel = [np.asarray(reference_mel, dtype=np.float32)]
  File "D:\Anaconda3\envs\tf1.6\lib\site-packages\numpy\core\numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'training_data/mels\\speech-mel-00001.npy'
